### ISSUE TITLE
Reflected shots cause walls to be threatening

### ISSUE THREAD

**Issue by amylizzle** [stonepillars/goon-flock#295]
### Labels

[BUG]

### Description

Walls are marked by the protection component

### Steps to reproduce

1. Convert walls in a room
2. Have a drone shoot something and miss
3. Shot bounces off of the flock walls
4. Hits another flock thing
5. 
![image](https://user-images.githubusercontent.com/3855802/168442256-f7b2d42d-f361-4fdb-94b8-d6794885d268.png)

### Expected Behavior

Reflected shots probably shouldn't count for threats? or something

**Comment by FlameArrow57** [comment]
I think ideally reflected projectiles should be retaining their original shooter? Ex. someone shoots a projectile, and flockdrones report the person as having attacked every wall hit.

It just happens that Flock walls can reflect projectiles, don't know about any other wall reflecting, but ex. use case otherwise would be for logs, which do keep track of shooter I believe, in which case they would be wrong here.

**Comment by amylizzle** [comment]
@stonepillars suggested just throwing an `ismob()` check on the protection component. I would add `iscritter()` to that also, just in case.
